Add base logic
rancher/per-host-subnet pull request #1
Opened 2017-09-15 07:45 UTC by niusmallnan

https://github.com/rancher/rancher/issues/9153

2017-09-21 07:46 UTC, leodotcloud requested changes

2017-09-21 07:46 UTC, leodotcloud commented on api.go
> +type APIServer struct {
Let's just get rid of this whole API server for now. We can revisit this later.
Two things I want to achieve later: 
- Improve upon https://github.com/leodotcloud/log to have an inbuilt server which listens on some configurable port, but listens only on localhost.
- Have a generic healthcheck framework and server that we can integrate in all of our microservices.

2017-09-21 07:46 UTC, leodotcloud commented on hostnat/watcher.go
> +	mu        sync.Mutex
Do we really need this? We are not sharing this between different threads.

2017-09-21 07:46 UTC, leodotcloud commented on hostnat/watcher.go
> +	ipsetPath, err := exec.LookPath("ipset")
We can have the assumption that ipset binary will be present, no need to check every time.

2017-09-21 07:46 UTC, leodotcloud commented on hostnat/watcher.go
> +func (w *watcher) diffIPSetEntries(ipsetPath string, selfHost metadata.Host, allHosts []metadata.Host) (toAddEntries []string, toDelEntries []string, err error) {
Inputs: current, desired
Outputs: toAdd, toDel

Passing in ipsetPath is not making this function modular.

2017-09-21 07:46 UTC, leodotcloud commented on hostnat/watcher.go
> +	r := regexp.MustCompile("(?m)^(.*\n)*Members:\n")
looks like we can get the output of the list command in xml. `ipset list -o xml`
I guess parsing an XML output is more efficient than regex? May be you can write two functions, one using regex and another using xml parser and run them in *_test.go with a large ipset and check the performance?

2017-09-21 07:46 UTC, leodotcloud commented on hostnat/watcher.go
> +	for _, e := range toAddEntries {
ipset supports swapping, not sure if it's very useful here. That's what we do in network-policy. If it helps you simply the code here, you can use it. Totally up to you.

2017-09-21 07:46 UTC, leodotcloud commented on main.go
> +		cli.StringFlag{
As mentioned above, let's get rid of this for now.

2017-09-21 07:46 UTC, leodotcloud commented on main.go
> +	listenPort := ctx.String("listen")
See above: remove.

2017-09-21 07:46 UTC, leodotcloud commented on package/Dockerfile
> +FROM rancher/agent-base:v0.3.0
We don't need `Dockerfile` for this. Can you please package it as a binary like ipsec/vxlan and make a separate PR to include this in `rancher/net`?

2017-09-21 07:46 UTC, leodotcloud commented on routeupdate/hostgw/hostgw.go
> +	mu sync.Mutex
is the mutex needed?

2017-09-21 07:46 UTC, leodotcloud commented on routeupdate/hostgw/hostgw.go
> +func NewInst(m metadata.Client) (*HostGw, error) {
`func NewRouteUpdater` or just `func New`?

2017-09-26 09:53 UTC, niusmallnan commented on package/Dockerfile
> +FROM rancher/agent-base:v0.3.0
Ok, I made a PR https://github.com/rancher/rancher-net/pull/78 .
Need merge `per-host-subnet` before you can review `rancher-net` PR.

2017-09-27 04:17 UTC, leodotcloud approved these changes
LGTM

2017-09-27 04:18 UTC, merged